name: CI (Dev branch)

on:
  push:
    branches:
      - dev

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest black pyflakes

      - name: Lint (pyflakes)
        run: python -m pyflakes app || true

      - name: Format check (black)
        run: python -m black --check app || true

      - name: Run tests
        run: pytest -q

      - name: Build Docker image
        run: docker build -t ai-infer:dev .

